services:
  database:
    container_name: database-container
    image: pgrouting/pgrouting:12-3.0-3.0.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  data:
    external: true
    name: ${POSTGRES_DB}_data
